regions:
  - us-east-1
  - global

account-blocklist:
  - "999999999999"

accounts:
  "125168806853":
    presets: []
    filters:
      IAMUser:
        - "Kindee"
      IAMUserPolicyAttachment:
        - "Kindee -> *"
      IAMAccessKey:
        - "AKIAR2JFENPCRYE7Q7WA"
      IAMLoginProfile:
        - "Kindee"
